### PR TITLE
fix: Automatically recover expired sessions.

### LINKED ISSUE #27: Token refresh does not work
Setting up a nextjs app with supabase based on the example in the supbase repository, I get a functioning app, but the token refresh does not seem to work. After one hour the user is being logged out as the token is not valid anymore.

https://github.com/supabase/supabase/tree/master/examples/nextjs-with-supabase-auth

### PR DESCRIPTION
**Pull request by thorwebdev**
## What kind of change does this PR introduce?

Fixes #27 

- Automatically recover expired sessions on page load using the refresh token

### CODE REVIEW

**Comment by kiwicopple** [comment]
Woo! Thanks Thor

**Comment by kiwicopple** [comment]
That's a good idea - it must be possible since `swr` does something similar: https://swr.vercel.app/

Perhaps we can discuss in a new issue?

**Comment by 10000multiplier** [comment]
#70 made a new issue

**Comment by kiwicopple** [comment]
Thanks @10000multiplier 🙏

**Pull request merged**
