### PR TITLE
Possible change of error message when getting session fails

### LINKED ISSUE #240: Annoy error message without a error.
# Chore

## Describe the chore

https://github.com/supabase/gotrue-js/blob/e440a90099b5c138ac841348e1f1bb5b02f58608/src/GoTrueClient.ts#L109

the library is reporting an error and it should be a warn because it doesn't stop the execution of the app.

### PR DESCRIPTION
**Pull request by J0**
## What kind of change does this PR introduce?

Changes  the console log on error in getting session from URL from error -> to warn in order to fix  #240 . Seems more a DX thing so looping in Thor and Silentworks.

## What is the current behavior?

Please link any relevant issues here.

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Review by kangmingtay — COMMENTED** [review]
should we just throw the error instead? @thorwebdev @silentworks

**Review by silentworks — APPROVED** [review]

**Comment by silentworks** [comment]
A warn seems fair to me in this context.

**Comment by kangmingtay** [comment]
Actually, hang on i think we should throw this error instead based on this [issue](https://github.com/supabase/gotrue/issues/536)

**Comment by pixtron** [comment]
@kangmingtay it was a good intention to throw the error. the thing is: the constructor is sync and the error is thrown when the async getSessionFromUrl resolves. At this point the constructor already returned and therefore there is no chance to catch that error. Probably best is to revert back to logging it?. There is a [workaround](https://github.com/supabase/gotrue/issues/536#issuecomment-1200156629) how catch these errors. Check this simplified example:

```js
class Client {
  constructor() {
    this.getSessionFromUrl().then(({error}) => {
      if (error) {
        throw error;
      }
    });
  }
  
  async getSessionFromUrl() {
    try {
      await new Promise(resolve => setTimeout(resolve, 1000));
      throw new Error('No expires_in detected.');
      
      return { session: { access_token: 'xxx' }, error: null}
    } catch(e) {
      return { session: null, error: e };
    }
  }
}

try { 
  const client = new Client();
} catch(error) {
  console.log('can\'t catch it here', error);
}
```

**Pull request merged**
