### PR TITLE
fix: signout should remove session if user doesn't exist

### LINKED ISSUE #540: No way to clear expired User. Using auth.signOut fails
# Bug report

## Describe the bug

If you call supabase.auth.signOut() with an expired JWT, GoTrue fails with:
AuthApiError: invalid JWT: unable to parse or verify signature, token

The problem is that the stale user session is still stored in the auth module.
There is no way to remove it with the API.

That means that now edge functions will fail because of the invalid JWT (even if an anonymous JWT would have worked).

This puts the browser client in a broken and unfixable state.

## Expected behavior

If GoTrue reports that the JWT is expired, then the user is signed out, and thet session should be cleared from supabase.auth
Alternatively I could catch the error, but would need an API to clear the current session from supabase.auth

## System information

- Browser Chrome
- Version of supabase-js: 2.0.0

### PR DESCRIPTION
**Pull request by kangmingtay**
## What kind of change does this PR introduce?
* Fixes #540, #520

### CODE REVIEW

**Comment by j4w8n** [comment]
Sweet! This seems to resolve enough of 540 to close it, and all of 520 🎉; but not #524, as you stated it would in the description.

I fetched your PR locally and tested. If you add the below code in the `signOut` test (not the test you added, but the one right above it), it still returns user data with `getUser()` after the user is signed out. From the client output, you'll see where the `headers` and `admin.headers` still have the logged-out user's jwt. This is the main concern of 524.

```diff
const res = await authWithSession.signOut()
expect(res).toBeTruthy()
+ console.log(authWithSession)
+ const { data: { user } } = await authWithSession.getUser()
+ expect(user).toBe(null)
```

I was able to "reset" the `GoTrueClient` header by doing `this.headers = { ...DEFAULT_HEADERS }` in `_removeSession()`. But that still leaves the `GoTrueAdminApi` headers; which I wasn't able to access via `this.admin.headers` from the GoTrueClient since it's protected.

Also, when using the supabase-js client in a project, the `this.changedAccessToken` property still contains the jwt. See Gary's output in 524 [here](https://github.com/supabase/gotrue-js/issues/524#issue-1428366104).

I'd say we'll need to make a change in the supabase-js repo as well if we want to resolve 524. See comment [here](https://github.com/supabase/gotrue-js/issues/524#issuecomment-1304857759) for how I was able to do that on the fly. Might not be the way you want to resolve it - I was just experimenting.

**Comment by thorwebdev** [comment]
I think the root of this issue is https://github.com/supabase/supabase/issues/5990

**Review by thorwebdev — APPROVED** [review]
LGTM. I think we'll need to fix #524 separately as it will require changes to supabase-js.

**Comment by kangmingtay** [comment]
@j4w8n fixed #524 in [this commit](https://github.com/supabase/gotrue-js/pull/541/commits/0ad574d09d2e44b0ba313eecc47e8d3bb4288f58), turns out the `_request` wrapper method was directly using the headers object passed into it, and since objects in javascript are passed by reference instead of by value, we need to copy it into a new object first

thanks for catching this btw! i've updated the test suite too to prevent regression in the future

**Pull request merged**
