### PR TITLE
Fix bugs

### LINKED ISSUE #38: Fix globalThis for older browsers/Node environments
# Bug report

## Describe the bug

Looks like globalThis isn't globally supported

https://github.com/jsdom/jsdom/issues/2795

## To Reproduce

https://codesandbox.io/s/github/supabase/supabase/tree/master/examples/nextjs-todo-list

Perhaps we should we polyfill this, or we need to change it from `globalThis`?

### LINKED ISSUE #41: process is not defined
# Bug report

## Describe the bug

Causes errors in some environments

### PR DESCRIPTION
**Pull request by kiwicopple**
## What kind of change does this PR introduce?

- Fix #38 
- Fix #41

### CODE REVIEW

**Comment by kiwicopple** [comment]
pr: @thorwebdev | @soedirgo 

TBH the "globalThis" is a new one to me. 

#38 links to this: https://codesandbox.io/s/github/supabase/supabase/tree/master/examples/nextjs-todo-list

I suspect if `globalThis` isn't supported, perhaps `localStorage` isn't either? Not really sure what to do in these situations. Hopefully this is a step closer. #kaizen

**Comment by kiwicopple** [comment]
Fixes: 

https://github.com/supabase/supabase-js/issues/113
https://github.com/supabase/supabase-js/issues/89

**Review by soedirgo — APPROVED** [review]
If we can polyfill localStorage, we probably won't need to polyfill globalThis since we can just use `localStorage` without fully qualifying it. But I can't find an isomorphic localStorage solution :/

There's [node-localstorage](https://www.npmjs.com/package/node-localstorage) but it's possible that the context is a browser that doesn't support localStorage.

**Review by thorwebdev — APPROVED** [review]
TIL 🤯 
LGTM

**Pull request merged**
