### PR TITLE
feat: add SSO PKCE

### PR DESCRIPTION
**Pull request by J0**
## What kind of change does this PR introduce?

Companion PR to: https://github.com/supabase/gotrue/pull/1137

Server-Side PR: PKCE https://github.com/supabase/gotrue/pull/1137

### CODE REVIEW

**Comment by remorses** [comment]
Thank you for this PR, currently `signInWithSSO` is broken when using PKCE, it seems `detectSessionInUrl` does not detect `access_token` when using the auth helpers in next.js

**Comment by tedsmitt** [comment]
What's the status on this PR? I could really do with it being merged in! Anything I can help with? 😄

**Comment by J0** [comment]
Hey @tedsmitt,

Thanks for the offer of help but I don't think there's anything that can be done at the moment which would move the needle forward. We'll get this reviewed once our next Auth deploy goes out  which should be in a week or two.

Thanks for your patience!

**Comment by remorses** [comment]
Did the new gotrue version get deloyed? How can we keep track of deployments?

**Comment by remorses** [comment]
Any update? I would love to start using SSO with Next.js

**Review by kangmingtay — APPROVED** [review]

**Pull request merged**
