### PR TITLE
Update GoTrueClient.ts

### PR DESCRIPTION
**Pull request by bigpreshy**
## What kind of change does this PR introduce?

docs update: This removes unnecessary word.

## What is the current behavior?

Please link any relevant issues here.

## What is the new behavior?

Feel free to include screenshots if it includes visual changes.

## Additional context

Add any other context or screenshots.

### CODE REVIEW

**Comment by kiwicopple** [comment]
thanks!

**Comment by bigpreshy** [comment]
I really love this project.

**Comment by kiwicopple** [comment]
❤️ thanks @bigpreshy - and if you haven't already claimed some swag, you can send your tshirt size and postal address to swag@supabase.io. Just mention this PR and we'll send you something nice :)

**Comment by bigpreshy** [comment]
🥳🥳 thanks.  Appreciated.  I have sent the email.

I will start telling people around me about this project.  Already got some blog post ideas 💡 I will work on.

**Pull request merged**
